#!/usr/bin/perl
use DBI;
$hostname='localhost';
$port=3306;
$username='pw1';
$password='episunsa';
$database='pw1';
$dsn = "DBI:mysql:database=$database;host=$hostname;port=$port";

$dbh = DBI->connect($dsn, $username, $password) or die("No se pudo conectar!");
$sth = $dbh->prepare("select * from Customers");
$sth->execute();

print "Content-type: text/html\n\n";
print <<HTML;
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>TestMySql</title>
</head>
<body>
HTML
while(  @res = $sth->fetchrow_array()){
  printf "@res <BR>\n";
}
print <<HTML;
</body>
</html>
HTML
$dbh->disconnect();
